"""
TERA-STRIPE Pytest Configuration & Shared Fixtures
====================================================
Provides reusable fixtures for M1 ingestion tests: temporary directories,
SQLite-backed database sessions, and sample station metadata.
"""

from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

import pytest

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Force SQLite fallback for all tests
os.environ["USE_POSTGIS"] = "false"
os.environ["ENVIRONMENT"] = "testing"


@pytest.fixture
def tmp_dir(tmp_path: Path) -> Path:
    """Provide a clean temporary directory for test artifacts."""
    return tmp_path


@pytest.fixture
def sample_station_dir(tmp_path: Path) -> Path:
    """
    Create a temporary directory simulating STN_104B with a couple of
    minimal JPEG files for lightweight tests that don't need the full
    fixture suite.
    """
    station_dir = tmp_path / "STN_104B"
    station_dir.mkdir()

    try:
        import piexif
        from PIL import Image, ImageDraw

        for i in range(3):
            img = Image.new("RGB", (320, 240), (50 + i * 40, 80, 30 + i * 20))
            draw = ImageDraw.Draw(img)
            draw.rectangle([50 + i * 30, 50, 150 + i * 30, 150], fill=(200, 180, 50))

            exif_dict = {
                "0th": {
                    piexif.ImageIFD.Make: b"TestCam",
                    piexif.ImageIFD.Model: b"TC-100",
                    piexif.ImageIFD.ImageDescription: f"Serial:SN_TEST;Temp:{15.0 + i}C".encode(),
                },
                "Exif": {
                    piexif.ExifIFD.DateTimeOriginal: f"2026:02:14 0{i+1}:00:00".encode(),
                    piexif.ExifIFD.Flash: 0,
                },
                "GPS": {},
                "1st": {},
            }
            exif_bytes = piexif.dump(exif_dict)
            filepath = station_dir / f"IMG_TEST_{i:04d}.JPG"
            img.save(str(filepath), "JPEG", exif=exif_bytes, quality=80)

    except ImportError:
        # If piexif/Pillow are missing, create empty JPEG-like files
        for i in range(3):
            filepath = station_dir / f"IMG_TEST_{i:04d}.JPG"
            filepath.write_bytes(b"\xff\xd8\xff\xe0" + b"\x00" * 100)

    return station_dir


@pytest.fixture
def db_engine():
    """Create an in-memory SQLite engine with all tables initialized."""
    from src.m7_database import Base, get_engine, init_db

    engine = get_engine(url="sqlite:///:memory:")
    init_db(engine)
    return engine


@pytest.fixture
def db_session(db_engine):
    """Provide a scoped SQLAlchemy session on in-memory SQLite."""
    from src.m7_database import get_session_factory

    SessionLocal = get_session_factory(db_engine)
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()


@pytest.fixture
def full_fixture_dir() -> Path:
    """
    Return the path to the full fixture directory generated by
    ``scripts/create_test_fixtures.py``.  Skips the test if the
    fixtures haven't been generated yet.
    """
    fixture_dir = PROJECT_ROOT / "data" / "raw_camera_traps" / "STN_104B"
    if not fixture_dir.is_dir() or len(list(fixture_dir.glob("*.JPG"))) == 0:
        pytest.skip(
            "Full fixtures not found. Run: python scripts/create_test_fixtures.py"
        )
    return fixture_dir
